language: scala
jdk:
- oraclejdk8
scala:
- 2.11.11
script:
- sbt --warn ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.6.0 +test
- sbt --warn ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.6.1 +test
- sbt --warn ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.6.2 +test
after_success:
- ! '[[ $TRAVIS_BRANCH == "master" ]] && { sbt +publish; };'
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
sudo: false

